//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditAccount()
        {
            this.CreditStatements = new HashSet<CreditStatement>();
            this.PayCredits = new HashSet<PayCredit>();
        }
    
        public string CreditAccountNo { get; set; }
        public string LoginID { get; set; }
        public Nullable<int> CreditPoint { get; set; }
        public string CreditType { get; set; }
        public Nullable<float> CreditBalance { get; set; }
        public Nullable<float> CreditLimit { get; set; }
    
        public virtual LogIn LogIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditStatement> CreditStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayCredit> PayCredits { get; set; }
    }
}
