//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bankEntities : DbContext
    {
        public bankEntities()
            : base("name=bankEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<CreditAccount> CreditAccounts { get; set; }
        public virtual DbSet<CreditStatement> CreditStatements { get; set; }
        public virtual DbSet<LogIn> LogIns { get; set; }
        public virtual DbSet<PayCredit> PayCredits { get; set; }
        public virtual DbSet<Statement> Statements { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
