//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserID { get; set; }
        public string LoginID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string AddrStreet { get; set; }
        public string AddrCity { get; set; }
        public string AddrState { get; set; }
        public string Zipcode { get; set; }
    
        public virtual LogIn LogIn { get; set; }
    }
}
